title: d3h1 Blog
author: dohun0310
email: d3h1@d3h1.com

permalink: :title

plugins:
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%Y년 %-m월 %-d일"
  date_format_short: "%-m월 %-d일"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
